### ISSUE TITLE
Query fails with IO timeout on Forge modpack server

### ISSUE THREAD

**Issue by chloeruka** [xrjr/mcutils#27]
Hi there, as noted over in itzg/mc-monitor#22 I encounter a problem when running the `query` protocol against a Forge server:

```
root@d89b9e0a7935:/go# time mcutils query full <HOST> 25565
Error : read udp 172.17.0.2:59234->45.32.240.165:25565: i/o timeout.
Usage : mcutils query <basic|full> <hostname> <port>

real    0m5.017s
user    0m0.003s
sys     0m0.000s
```

Same result regardless of `basic` or `full` `query` request. It's pretty clear it's hitting the default 5 second timeout but `ping` seems to work just fine. For easier repro the `ping` result is available in a gist here: https://gist.github.com/chloeruka/c892c718204260faa6a578f7983ad654

mcutils version: `mcutils v1.3.2`
Minecraft server version: `1.16.5`
Server detail: Forge Mod Loader (modded) running [Enigmatica 6](https://www.curseforge.com/minecraft/modpacks/enigmatica6) v1.5.1

If I find the time to investigate this one this long weekend I'll add whatever I find.

**Comment by chloeruka** [comment]
Thanks for your work on this library by the way! 💙

**Comment by xrjr** [comment]
Hi, thank you for opening an issue.

I created a fresh Enigmatica 6 v1.5.1 server, but I can't reproduce the issue. This works fine for me.

The only way I get I/O timeout is when I disable query in the `server.properties`. Query is disabled by default, have you enabled it ? If this is the case, you should see this line in your logs at startup :

```
[14:32:45] [Query Listener #1/INFO] [minecraft/QueryThread]: Query running on 0.0.0.0:25565
```

In my case I had to completely stop the server, set `enable-query=true` in the properties, and then start the server manually to get it to work.

If you see this line in your logs, then I have a few questions :
- Does it work with any other query client ?
- Does the client has to resolve a SRV record ?
- Is the server running behind some kind of proxy (udp enabled) ?

I feel like the issue is a transmission problem rather than a protocol one.

**Comment by chloeruka** [comment]
Ohh, I'm so sorry, I didn't realise you had to enable query mode on the server props. I think you're completely right, my server.properties have `enable-query=false` as I guess it's the default. Thanks for letting me know, I'll close this out 🙇🏻😅

**Comment by xrjr** [comment]
Yes it is disabled by default. No problem, glad I could help 😁
